name: Feature request
description: Suggest an idea for this project
title: "[Feature request] :title"
labels: ["feature request"]
assignees:
  - 6tranov
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: exx. email@example.com
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is.
      placeholder: Tell me the problem.
      value: "I'm always frustrated when ..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like. A clear and concise description of what you want to happen.
      placeholder: Tell me the solution.
      value: "I want to use this software like ..."
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative
      description: Describe alternatives you've considered. A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Tell me the alternative.
      value: "I came up with alternatives like ..."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Additional context. Add any other context or screenshots about the feature request here.
      placeholder: tell me additional contexts if you have.
      value: "I don't have any additional context."
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true